name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install needed packages
      run: sudo apt-get install mingw-w64 pkg-config libhyperscan-dev

    - name: Build
      run: ./build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: |
          SecretScanner-*
          config.yaml
